apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ozecoqki
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ozecoqki:7ab9667061a467711aa6de76f83afea56f3db3dc@sha256:f9f6a70f802e570fda85eebb9a3169db92a55f616cd424e1c5aaa85b76e1ea15
          name: container-image
